/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expo;
import  Clases.mantenimientosgruas;
import javax.swing.JOptionPane;
import Clases.Limitador;
import java.awt.MouseInfo;
import java.awt.Point;

/**
 *
 * @author Geovany Fuentes
 */
public class gruas extends javax.swing.JFrame {

    /**
     * Creates new form gruas
     */
    public gruas() {
        initComponents();
        limitar();
        txtnombregrua.grabFocus();
    }
    public void limitar(){
    txtplaca.setDocument(new Limitador(txtplaca, 6));
    txtaño.setDocument(new Limitador(txtaño, 4));
    txttarjeta.setDocument(new Limitador(txttarjeta, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialPanel1 = new de.craften.ui.swingmaterial.MaterialPanel();
        lblcolor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblplaca = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        txtnombregrua = new de.craften.ui.swingmaterial.MaterialTextField();
        txtplaca = new de.craften.ui.swingmaterial.MaterialTextField();
        txtaño = new de.craften.ui.swingmaterial.MaterialTextField();
        txttarjeta = new de.craften.ui.swingmaterial.MaterialTextField();
        txtcolor = new de.craften.ui.swingmaterial.MaterialTextField();
        materialPanel2 = new de.craften.ui.swingmaterial.MaterialPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        iconClose = new de.craften.ui.swingmaterial.MaterialIconButton();
        btnconductores = new de.craften.ui.swingmaterial.MaterialButton();
        materialPanel3 = new de.craften.ui.swingmaterial.MaterialPanel();
        btnagregar = new de.craften.ui.swingmaterial.MaterialButton();
        materialButton1 = new de.craften.ui.swingmaterial.MaterialButton();
        btneliminar = new de.craften.ui.swingmaterial.MaterialButton();
        btnmodificar = new de.craften.ui.swingmaterial.MaterialButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        materialPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcolor.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lblcolor.setText("Color Grua:");
        materialPanel1.add(lblcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel1.setText("Tarjeta de Circulacion:");
        materialPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel2.setText("Año:");
        materialPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        lblplaca.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lblplaca.setText("Numero de Placa:");
        materialPanel1.add(lblplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        lblnombre.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lblnombre.setText("Nombre:");
        materialPanel1.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        txtnombregrua.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        materialPanel1.add(txtnombregrua, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 177, 61));

        txtplaca.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        materialPanel1.add(txtplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 180, 60));

        txtaño.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        materialPanel1.add(txtaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 180, 60));

        txttarjeta.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        materialPanel1.add(txttarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 180, 60));

        txtcolor.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        materialPanel1.add(txtcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 180, 50));

        materialPanel2.setBackground(new java.awt.Color(187, 222, 251));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel3.setText("Anade una grua");

        javax.swing.GroupLayout materialPanel2Layout = new javax.swing.GroupLayout(materialPanel2);
        materialPanel2.setLayout(materialPanel2Layout);
        materialPanel2Layout.setHorizontalGroup(
            materialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, materialPanel2Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        materialPanel2Layout.setVerticalGroup(
            materialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, materialPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(23, 23, 23))
        );

        materialPanel1.add(materialPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 110));

        getContentPane().add(materialPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 500, 450));

        jPanel1.setBackground(new java.awt.Color(25, 118, 210));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        iconClose.setText("materialIconButton1");
        iconClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(714, Short.MAX_VALUE)
                .addComponent(iconClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(iconClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 60));

        btnconductores.setBackground(new java.awt.Color(204, 204, 204));
        btnconductores.setText("Conductores");
        btnconductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconductoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnconductores, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 180, 60));

        btnagregar.setBackground(new java.awt.Color(204, 204, 204));
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        materialButton1.setBackground(new java.awt.Color(204, 204, 204));
        materialButton1.setText("Buscar");
        materialButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton1ActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(204, 204, 204));
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnmodificar.setBackground(new java.awt.Color(204, 204, 204));
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout materialPanel3Layout = new javax.swing.GroupLayout(materialPanel3);
        materialPanel3.setLayout(materialPanel3Layout);
        materialPanel3Layout.setHorizontalGroup(
            materialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, materialPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(materialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(materialPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(materialPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(materialButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        materialPanel3Layout.setVerticalGroup(
            materialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(materialPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(materialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(materialPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(materialPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(materialPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 250, 130));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iconCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconCloseActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_iconCloseActionPerformed
    private int x;
    private int y;
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x , point.y -y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();

    }//GEN-LAST:event_jPanel1MousePressed

    private void btnconductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconductoresActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
                new conductores().setVisible(true);
                this.hide();
    }//GEN-LAST:event_btnconductoresActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        mantenimientosgruas obj = new mantenimientosgruas();
        if (txtnombregrua.getText().equals("")||txtplaca.equals("") || txtaño.getText().equals("")|| txttarjeta.getText().equals("") || txtcolor.equals("")) {
            JOptionPane.showMessageDialog(this,"Su textbox esta vacio por favor ingrese datos ","Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            obj.setNombregrua(txtnombregrua.getText());
            obj.setNumeroplacas(txtplaca.getText());
            obj.setAño(txtaño.getText());
            obj.setTarjetacirculacion(txttarjeta.getText());
            obj.setColorgrua(txtcolor.getText());
        }
        if (obj.guardargruas()) {
            JOptionPane.showMessageDialog(this, "Datos guardados ","Exito", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Error al guardar datos ","Atención",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnagregarActionPerformed

    private void materialButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton1ActionPerformed
        // TODO add your handling code here:
        mantenimientosgruas obj = new mantenimientosgruas();
        obj.setNombregrua(txtnombregrua.getText());
        if (obj.consultargruas()) {
        txtnombregrua.setText(obj.getNombregrua());
        txtplaca.setText(obj.getNumeroplacas());
        txtaño.setText(obj.getAño());
        txttarjeta.setText(obj.getTarjetacirculacion());
        txtcolor.setText(obj.getColorgrua());
 
        }
        else{
            JOptionPane.showMessageDialog(this, "Datos no encontrados ","Atención",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_materialButton1ActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
               mantenimientosgruas obj = new mantenimientosgruas();
        obj.setNombregrua(txtnombregrua.getText());
        int eliminar = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar? ",
                "Atencion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        
        if (eliminar == 0) {
            if (obj.eliminargruas()) {
                JOptionPane.showMessageDialog(this,"Datos eliminados ","Exito", JOptionPane.OK_OPTION);
                
            }else{
                JOptionPane.showMessageDialog(this, "Error al eliminar ","Atención",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
          mantenimientosgruas obj = new mantenimientosgruas();
        obj.setNombregrua(txtnombregrua.getText());
        obj.setNumeroplacas(txtplaca.getText());
        obj.setAño(txtaño.getText());
        obj.setTarjetacirculacion(txttarjeta.getText());
        obj.setColorgrua(txtcolor.getText());
     
        if (obj.modificargruas()) {
            
            JOptionPane.showMessageDialog(this, "Datos modificados ", "Atención",JOptionPane.INFORMATION_MESSAGE);
            txtnombregrua.setText("");
            txtplaca.setText("");
            txtaño.setText("");
            txttarjeta.setText("");
            txtcolor.setText("");
        }else{
            JOptionPane.showMessageDialog(this, "Error al modificar datos de la grua ","Atención",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gruas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gruas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gruas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gruas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gruas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.craften.ui.swingmaterial.MaterialButton btnagregar;
    private de.craften.ui.swingmaterial.MaterialButton btnconductores;
    private de.craften.ui.swingmaterial.MaterialButton btneliminar;
    private de.craften.ui.swingmaterial.MaterialButton btnmodificar;
    private de.craften.ui.swingmaterial.MaterialIconButton iconClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcolor;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblplaca;
    private de.craften.ui.swingmaterial.MaterialButton materialButton1;
    private de.craften.ui.swingmaterial.MaterialPanel materialPanel1;
    private de.craften.ui.swingmaterial.MaterialPanel materialPanel2;
    private de.craften.ui.swingmaterial.MaterialPanel materialPanel3;
    private de.craften.ui.swingmaterial.MaterialTextField txtaño;
    private de.craften.ui.swingmaterial.MaterialTextField txtcolor;
    private de.craften.ui.swingmaterial.MaterialTextField txtnombregrua;
    private de.craften.ui.swingmaterial.MaterialTextField txtplaca;
    private de.craften.ui.swingmaterial.MaterialTextField txttarjeta;
    // End of variables declaration//GEN-END:variables
}
