/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expo;

import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.JOptionPane;
import org.kordamp.ikonli.materialdesign.MaterialDesign;
import org.kordamp.ikonli.swing.FontIcon;
import principal.*;
import Clases.*;
/**
 *
 * @author Estudiante
 */
public class newuser extends javax.swing.JFrame {

    /**
     * Creates new form newuser
     */
    public newuser() {
        initComponents();
        FontIcon iconaccount = new FontIcon();
        iconaccount.setIkon(MaterialDesign.MDI_ACCOUNT);
        iconaccount.setIconSize(32);
        iconUser.setIcon(iconaccount);
        
        FontIcon iconkey = new FontIcon();
        iconkey.setIkon(MaterialDesign.MDI_KEY_VARIANT);
        iconkey.setIconSize(32);
        iconPass.setIcon(iconkey);
        
        FontIcon btnClose = new FontIcon();
        btnClose.setIkon(MaterialDesign.MDI_CLOSE_CIRCLE);
        btnClose.setIconSize(25);
        iconClose.setIcon(btnClose);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        lblcontraseñaolvidada = new javax.swing.JLabel();
        lblregistrarse = new javax.swing.JLabel();
        materialPanel1 = new de.craften.ui.swingmaterial.MaterialPanel();
        materialPanel3 = new de.craften.ui.swingmaterial.MaterialPanel();
        jLabel2 = new javax.swing.JLabel();
        txtusuario = new de.craften.ui.swingmaterial.MaterialTextField();
        txtcontrasena = new de.craften.ui.swingmaterial.MaterialPasswordField();
        iconUser = new javax.swing.JLabel();
        iconPass = new javax.swing.JLabel();
        btningresar = new de.craften.ui.swingmaterial.MaterialButton();
        materialPanel2 = new de.craften.ui.swingmaterial.MaterialPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        iconClose = new de.craften.ui.swingmaterial.MaterialIconButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 151, -1, -1));

        lblcontraseñaolvidada.setBackground(new java.awt.Color(255, 235, 59));
        lblcontraseñaolvidada.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblcontraseñaolvidada.setText("Recuperar Contraseña");
        lblcontraseñaolvidada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblcontraseñaolvidadaMousePressed(evt);
            }
        });
        getContentPane().add(lblcontraseñaolvidada, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        lblregistrarse.setBackground(new java.awt.Color(255, 235, 59));
        lblregistrarse.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblregistrarse.setText("Registrarse");
        lblregistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblregistrarseMousePressed(evt);
            }
        });
        getContentPane().add(lblregistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        materialPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        materialPanel3.setBackground(new java.awt.Color(187, 222, 251));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Inicio de Sesion");

        javax.swing.GroupLayout materialPanel3Layout = new javax.swing.GroupLayout(materialPanel3);
        materialPanel3.setLayout(materialPanel3Layout);
        materialPanel3Layout.setHorizontalGroup(
            materialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, materialPanel3Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(114, 114, 114))
        );
        materialPanel3Layout.setVerticalGroup(
            materialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, materialPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );

        materialPanel1.add(materialPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 90));

        txtusuario.setAccent(new java.awt.Color(33, 33, 33));
        txtusuario.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtusuario.setHint("Usuario");
        materialPanel1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 290, 70));

        txtcontrasena.setAccent(new java.awt.Color(33, 33, 33));
        txtcontrasena.setHint("Contrasena");
        materialPanel1.add(txtcontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 290, 70));
        materialPanel1.add(iconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 40, 40));
        materialPanel1.add(iconPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 40, 30));

        btningresar.setBackground(new java.awt.Color(158, 158, 158));
        btningresar.setText("Acceder");
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });
        materialPanel1.add(btningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 180, 70));

        getContentPane().add(materialPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 420, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expoimagenes/user.png"))); // NOI18N

        javax.swing.GroupLayout materialPanel2Layout = new javax.swing.GroupLayout(materialPanel2);
        materialPanel2.setLayout(materialPanel2Layout);
        materialPanel2Layout.setHorizontalGroup(
            materialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, materialPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        materialPanel2Layout.setVerticalGroup(
            materialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, materialPanel2Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        getContentPane().add(materialPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 360));

        jPanel1.setBackground(new java.awt.Color(25, 118, 210));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        iconClose.setText("materialIconButton1");
        iconClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(580, Short.MAX_VALUE)
                .addComponent(iconClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(iconClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblcontraseñaolvidadaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcontraseñaolvidadaMousePressed
       this.setVisible(false);
       new recorverpass().setVisible(true);
       hide();
    }//GEN-LAST:event_lblcontraseñaolvidadaMousePressed

    private void lblregistrarseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregistrarseMousePressed
        this.setVisible(false);
        new CrearCuenta().setVisible(true);
        hide();
    }//GEN-LAST:event_lblregistrarseMousePressed
    private int x;
    private int y;
    
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
        
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x , point.y -y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void iconCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconCloseActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_iconCloseActionPerformed

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        // TODO add your handling code here:
         txtusuario.setEnabled(false);
        txtcontrasena.setEnabled(false);
        btningresar.setEnabled(false);
        if (login.validar_ingreso()) {
            // Inicir sesión
            RangoUsuario obj = new RangoUsuario();
            if (obj.ObtenerRango()) {
                if (obj.getId_rango() ==1) {
                    System.out.println("Hola muy buenas, aun no hay form xdxdx");
                }
                else if(obj.getId_rango() ==2){
                    Principal menu = new Principal();
                    new Principal().setVisible(true);
                }
            }
            
//            Principal menu = new Principal();
//
//            new Principal().setVisible(true);
            dispose();
        } else {
            System.out.println("xD");
            txtusuario.setEnabled(true);
            txtcontrasena.setEnabled(true);
            btningresar.setEnabled(true);
        }
    }//GEN-LAST:event_btningresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.craften.ui.swingmaterial.MaterialButton btningresar;
    private de.craften.ui.swingmaterial.MaterialIconButton iconClose;
    private javax.swing.JLabel iconPass;
    private javax.swing.JLabel iconUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblcontraseñaolvidada;
    private javax.swing.JLabel lblregistrarse;
    private de.craften.ui.swingmaterial.MaterialPanel materialPanel1;
    private de.craften.ui.swingmaterial.MaterialPanel materialPanel2;
    private de.craften.ui.swingmaterial.MaterialPanel materialPanel3;
    public static de.craften.ui.swingmaterial.MaterialPasswordField txtcontrasena;
    public static de.craften.ui.swingmaterial.MaterialTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
