/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expo;

import Clases.recuperarcontraseña;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sun.security.util.Password;

import java.awt.MouseInfo;
import java.awt.Point;
import org.kordamp.ikonli.materialdesign.MaterialDesign;
import org.kordamp.ikonli.swing.FontIcon;
/**
 *
 * @author Estudiante
 */
public class recorverpass extends javax.swing.JFrame {

    String[] data;
    
    /**
     * Creates new form recorverpass
     */
    public recorverpass() {
        initComponents();
        
        FontIcon see = new FontIcon();
        see.setIkon(MaterialDesign.MDI_EYE);
        see.setIconSize(24);
        iconEye.setIcon(see);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialTextField1 = new de.craften.ui.swingmaterial.MaterialTextField();
        jPanel1 = new javax.swing.JPanel();
        iconClose = new de.craften.ui.swingmaterial.MaterialIconButton();
        materialPanel1 = new de.craften.ui.swingmaterial.MaterialPanel();
        materialPanel2 = new de.craften.ui.swingmaterial.MaterialPanel();
        txtnombre = new de.craften.ui.swingmaterial.MaterialTextField();
        btnverficar = new de.craften.ui.swingmaterial.MaterialButton();
        txtpregunta = new de.craften.ui.swingmaterial.MaterialTextField();
        txtrespuesta = new de.craften.ui.swingmaterial.MaterialTextField();
        txtrecuperacion = new de.craften.ui.swingmaterial.MaterialTextField();
        iconEye = new de.craften.ui.swingmaterial.MaterialIconButton();
        materialButton2 = new de.craften.ui.swingmaterial.MaterialButton();

        materialTextField1.setText("materialTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 124, 0));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        iconClose.setText("materialIconButton1");
        iconClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(514, Short.MAX_VALUE)
                .addComponent(iconClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(iconClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 50));

        materialPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        materialPanel2.setBackground(new java.awt.Color(255, 152, 0));
        materialPanel1.add(materialPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 90));

        txtnombre.setAccent(new java.awt.Color(33, 33, 33));
        txtnombre.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtnombre.setHint("Usuario");
        materialPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 220, 70));

        btnverficar.setBackground(new java.awt.Color(255, 235, 59));
        btnverficar.setText("Verificar!");
        btnverficar.setToolTipText("");
        btnverficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverficarActionPerformed(evt);
            }
        });
        materialPanel1.add(btnverficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 180, 60));

        txtpregunta.setAccent(new java.awt.Color(33, 33, 33));
        txtpregunta.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtpregunta.setHint("Pregunta");
        materialPanel1.add(txtpregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 220, 70));

        txtrespuesta.setAccent(new java.awt.Color(33, 33, 33));
        txtrespuesta.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtrespuesta.setHint("Respuesta");
        materialPanel1.add(txtrespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 220, 70));

        txtrecuperacion.setAccent(new java.awt.Color(33, 33, 33));
        materialPanel1.add(txtrecuperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 220, 70));

        iconEye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconEyeActionPerformed(evt);
            }
        });
        materialPanel1.add(iconEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 50, 50));

        getContentPane().add(materialPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 460, 410));

        materialButton2.setBackground(new java.awt.Color(255, 235, 59));
        materialButton2.setText("Login");
        materialButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(materialButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 90, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iconCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconCloseActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_iconCloseActionPerformed
      private int x;
      private int y;
 
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x , point.y -y);
        
        
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();

    }//GEN-LAST:event_jPanel1MousePressed

    private void iconEyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconEyeActionPerformed
        // TODO add your handling code here:
         if (txtrespuesta.getText().equals(data[2])) {
            iconEye.setEnabled(false);
            txtrespuesta.setEnabled(false);
            txtrecuperacion.setText(data[0]);
        } else {
            JOptionPane.showMessageDialog(this, "Respuesta incorrecta.");
        }
    }//GEN-LAST:event_iconEyeActionPerformed

    private void btnverficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverficarActionPerformed
        // TODO add your handling code here:
         data = recuperarcontraseña.obtenerDatos(txtnombre.getText());
        if (data != null) {
            iconEye.setEnabled(false);
            txtnombre.setEnabled(false);
            txtpregunta.setText(data[1]);
            txtrespuesta.setEnabled(true);
            iconEye.setEnabled(true);

        }
    }//GEN-LAST:event_btnverficarActionPerformed

    private void materialButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton2ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new newuser().setVisible(true);
        hide();
    }//GEN-LAST:event_materialButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recorverpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recorverpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recorverpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recorverpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recorverpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.craften.ui.swingmaterial.MaterialButton btnverficar;
    private de.craften.ui.swingmaterial.MaterialIconButton iconClose;
    private de.craften.ui.swingmaterial.MaterialIconButton iconEye;
    private javax.swing.JPanel jPanel1;
    private de.craften.ui.swingmaterial.MaterialButton materialButton2;
    private de.craften.ui.swingmaterial.MaterialPanel materialPanel1;
    private de.craften.ui.swingmaterial.MaterialPanel materialPanel2;
    private de.craften.ui.swingmaterial.MaterialTextField materialTextField1;
    private de.craften.ui.swingmaterial.MaterialTextField txtnombre;
    private de.craften.ui.swingmaterial.MaterialTextField txtpregunta;
    private de.craften.ui.swingmaterial.MaterialTextField txtrecuperacion;
    private de.craften.ui.swingmaterial.MaterialTextField txtrespuesta;
    // End of variables declaration//GEN-END:variables
}
